meta version "v2.2,nothing";
meta name "hPhone";
//
meta platform "accelerometer,calendar,camera,compass,gyroscope,home,location,maps,media,microphone,motion,contacts,phone,radio,orientation,search,translation,musicandsounds,editoronly";

action go() {
  skip;
  meta private;
}

action go2() {
  skip;
  meta private;
}

action go3() {
  skip;
  meta private;
}

action show() {
  if box→is_init then {
    skip;
  }
  if true then {
    skip;
  }
}

action show2() {
  if box→is_init then {
    skip;
  }
  if true then {
    skip;
  }
}
var v : Number {
}
table thing {
  type = "Object";
  fields {
    f: String_field
  }
}
table thing2 {
  type = "Object";
  fields {
    f: String_field
  }
}

