meta version "v2.2,nothing";
meta name "Pavi";
meta color "#ff85bb65";
//
meta isLibrary "yes";
meta showAd "yes";
meta platform "current";
meta import data_pic {
  pub "epae"
  usage {
  }
  resolve base_string = ♻base_string with {
  }
  resolve json_core = ♻json_core with {
  }
}
meta import base_string {
  pub "dyeu"
  usage {
  }
}
meta import json_core {
  pub "jtfn"
  usage {
  }
}

action main() {
  "TouchDevelop is cool!" →post_to_wall;
}
var a : Color {
  is\_resource = true;
  url = "#ff29b23f";
}
table thing {
  type = "Object";
}

