meta version "v2.2,nothing";
meta name "I think this will post a kitten";
meta icon "shield";
meta color "#ffeedc82";
// This is my first app so idk if it will work
meta platform "current";

action main() {
  "TouchDevelop is cool!" →post_to_wall;
  if false then {
    if true→equals(false→equals(false→is_invalid→is_invalid→is_invalid→is_invalid)) then {
      foreach s in "Error try again later bro." where true do {
        phone→choose_phone_number→post_to_wall;
      }
    }
  }
  while true do {
    // I like fluffy kittens<3
    foreach c in art→pic2 where true do {
      for 0 ≤ i < 125 do {
        media→choose_picture→post_to_wall;
        // Yep this app be done!
      }
    }
  }
}
var a : Picture {
  is\_resource = true;
  url = "#ff02e511";
}
var red : Color {
  is\_resource = true;
  url = "#ffd30606";
}
var pic : Picture {
  is\_resource = true;
}
var c : Color {
  is\_resource = true;
  url = "#ffed0b0b";
}
var pic2 : Picture {
  is\_resource = true;
  url = "http://m.bing.com/search/Thumbnail.aspx?c=mpNQqcmT&w=320&h=480&i=http%3A%2F%2Ffiles.softicons.com%2Fdownload%2Fart-icons%2Fmaneki-neko-icons-by-icojoy%2Fpng%2F512%2Fcat_5.png";
}

